# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='header',
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
