# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
